(ns spellcast.spellbook)

(def book {[:C :D :P :W]             :dispel-magic,
           [:C :S :W :W :S]          :summon-elemental,
           [:C :dw]                  :magic-mirror,
           [:D :F :F :D :D]          :lightning-bolt,
           [:D :F :P :W]             :cure-heavy-wounds,
           [:D :F :W]                :cure-light-wounds,
           [:D :P :P]                :amnesia,
           [:D :S :F]                :confusion,
           [:D :S :F :F :F :C]       :disease,
           [:D :W :F :F :dd]         :blindness,
           [:D :W :S :S :S :P]       :delayed-effect,
           [:D :W :W :F :W :C]       :raise-dead,
           [:D :W :W :F :W :D]       :poison,
           [:F :F :F]                :paralysis,
           [:F :P :S :F :W]          :summon-troll,
           [:F :S :S :D :D]          :fireball,
           [:P]                      :shield,
           [:dp]                     :surrender,
           [:P :D :W :P]             :remove-enchantment,
           [:P :P :dw :ds]           :invisibility,
           [:P :S :D :D]             :charm-monster,
           [:P :S :D :F]             :charm-person,
           [:P :S :F :W]             :summon-ogre,
           [:P :W :P :F :S :S :S :D] :finger-of-death,
           [:P :W :P :W :W :C]       :haste,
           [:S :D]                   :missile,
           [:S :F :W]                :summon-goblin,
           [:S :P :F]                :anti-spell,
           [:S :P :F :P :S :D :W]    :permanency,
           [:S :P :P :C]             :time-stop,
           [:S :S :F :P]             :resist-cold,
           [:S :W :D]                :fear,
           [:S :W :W :C]             :fire-storm,
           [:W :D :D :C]             :lightning-bolt-once,
           [:W :F :P]                :cause-light-wounds,
           [:W :F :P :S :F :W]       :summon-giant,
           [:W :P :F :D]             :cause-heavy-wounds,
           [:W :P :P]                :counter-spell,
           [:W :S :S :C]             :ice-storm,
           [:W :W :F :P]             :resist-heat,
           [:W :W :P]                :protection-from-evil,
           [:W :W :S]                :counter-spell})
